import analyzers

# analyzers.aspect_of_harmony.spender( [
#   '3VWnfgKmDbxqRFYM'
# ] )

analyzers.tww1_brm.counts( [
  # '3VWnfgKmDbxqRFYM',
  # '9P1xnLQDCFaj8GYq',
  # 'qLJzYvgQwhXGfpVP',
  # 'zKL7t83HTdQPRkMa',
  # 'jGJtTpFnkD7qBYcw',
  # 'C3QKAxYmHDgF1aRM',
  # 'nvNVqTchMRLbAyZ2',
  # 'kMx89nQNTrYPg3mF',
  # 'Xk6hvgCybHGAnFm3',
  # 'p4yn3aXhcMjWbG1k',
  # 'cwQMNCmhgKT3ZRnq',
  # 'kc6aGNZrxpwbVyQA',
  # 'W1fhkGKdpt6LM9jY',
  # 'anGXxr3vBh8czqfy',
  # '7t4MpzXH3FKwxkch',
  # 'yQ2chx41PtDMTV9n',
  # 'wJrdL23tKWf4h8z7',
  # 'c8K1mqtdJFM4aHkP',
  # 'NvXc2DMqP1Zrakzw',
  # '8QNy4RmJqTrGhgxD',
  # 'WpgJzjxCBLbn3t24',
  'VXHxrPf938pWYBMc',
  'KBXLYNJHzC1cvWbV',
  'xtKDrk1Cpf6RczYA',
  'LNY1Hf7BGgDmjhKa',
  'VbKC7fpd2wF9XzkB',
  '7B8ZTVghLjfpCcFy',
  'AKc43VZG1JH7fkpd',
  'VCHrGT2RgW3Zv4kq',
  '6WbJCgZ3mHkM2tRn',
  'GqgnA43LaWNbY1R7',
  'gKDFYMHkxq6VABdJ',
  'K31vab6cTDRn9trk',
  'JV8c3dCakAjKqDY4',
  'MKZ9xCTykDbnaGpt',
  'ybrDBmMKQ3gkzwN7',
  'bHfgPvrhQtpDLjCw',
  'jq92c4ZzbGKg7tXN',
  'WPrVNvXTfR7kJ8xQ',
  'Km2DyJa4b97gkfHM',
  'a9hmD1x8HLkWVnGq',
  'WYbAm2cCJw1DpXgK',
  'MZAXwafgrWdGHJmR',
  'HxRDXrZWN4Bfd3vT',
  'VtcvLX4hA6rpw8kR',
  'ky4dzJGKM2NL91QH',
  'D9Tkdxtzw3FG8P2R',
] )

# analyzers.dual_threat.probability_at_count( [
#   'T9pZaqbDXjKMmWYg',
#   # 'Krf8vtAZFycxJL3a'
#   'amCgRMhq2v1Hn3dQ',
#   'vr9AQ4nNYh1m7Rfb',
#   'TDRzawK863Jb4k7N',
#   'Xd8aLMchkfwGpnYb',
#   'Mzrn8DaC6dhPcpHN',
#   'AJd8hxPaz34RmVtr',
#   'D6HqBGmXZwtvK3yL',
#   'jx1Vc4C8d72Xpz9F',
#   'jD6ctdg82AJkLaGP',
#   'hc3a48AJzQVKgPGv',
#   'mN1MTvD2QjawBZkt',
#   'DQ3W9r8MHt6CRYFA',
#   'tywx1KapgfGqnk48',
#   'QVJftk4cDrRTWY3F',
#   'ntq6mkTYjRwJFMp9',
#   'K8dxQAmN7rHtWqpn',
#   'HRf7pyznh28qmVwb',
#   'hZjMQGNVYKLkvH6b',
#   'a32pZrwgyG6jbhTn',
#   'gwZbyLDRNQ2CHAGP',
#   'xzMtT2kNvYrVhmqC',
#   'L9JBRq6Xgkj4xyKz',
#   'XF1jTKqbCVwrmgaB',
# ] )

# analyzers.dual_threat.probability_at_count( [ 'gqyW1GPaYfX3mzKn' ] )
